# ==== CONFIG ====

DEVKITPRO ?= /opt/devkitpro
DEVKITARM := $(DEVKITPRO)/devkitARM
LIBGBA := $(DEVKITPRO)/libgba

CC := $(DEVKITARM)/bin/arm-none-eabi-g++
OBJCOPY := $(DEVKITARM)/bin/arm-none-eabi-objcopy
GBAFIX := $(DEVKITPRO)/tools/bin/gbafix

# ==== BUILD VARS (GENERATED BY TRANSPILER) ====

BUILD_VARS ?= build/build_vars.mk
-include $(BUILD_VARS)

# ==== FALLBACKS ====

TARGET ?= game
SOURCE_C ?= build/game.c
OUT_DIR ?= $(patsubst %/,%,$(dir $(SOURCE_C)))
OUTPUT_ELF ?= $(OUT_DIR)/$(TARGET).elf
OUTPUT_GBA ?= $(OUT_DIR)/$(TARGET).gba
TIME_SCALE ?= 1.0

CFLAGS := -x c++ -std=gnu++17 \
          -mthumb -mthumb-interwork \
          -O2 -fno-exceptions -fno-rtti \
          -I$(LIBGBA)/include \
          -I./runtime \
          -DTIME_SCALE=$(TIME_SCALE)

LDFLAGS := -specs=gba.specs \
           -L$(LIBGBA)/lib \
           -lgba -lm

# ==== SOURCES ====

RUNTIME_SRC := \
    runtime/arduboy_compat.c \
    runtime/graphics.c \
    runtime/input.c \
    runtime/audio.c \
    runtime/gba_main.c

# ==== BUILD ====

all: $(OUTPUT_GBA)

$(OUTPUT_ELF): $(SOURCE_C) $(RUNTIME_SRC)
	@mkdir -p "$(dir $(OUTPUT_ELF))"
	$(CC) $(CFLAGS) $^ -o $@ $(LDFLAGS)

$(OUTPUT_GBA): $(OUTPUT_ELF)
	@mkdir -p "$(dir $(OUTPUT_GBA))"
	$(OBJCOPY) -O binary $< $@
	@if [ -x "$(GBAFIX)" ]; then \
		"$(GBAFIX)" "$@"; \
	else \
		echo "warning: gbafix not found at $(GBAFIX), skipping ROM fix step"; \
	fi

# ==== CLEAN ====

clean:
	find . -type f \( -name "*.elf" -o -name "*.gba" -o -name "*.sav" -o -name "*.srm" -o -name "*.sa1" -o -name "*.flash" -o -name "*.eep" \) -delete 2>/dev/null || true
	find . -type f \( -path "*/build/*.c" -o -path "*/build/*.o" -o -path "*/build/*.s" -o -path "*/build/*.ii" -o -path "*/build/*.mk" \) -delete 2>/dev/null || true

# ==== DEBUG ====

print-vars:
	@echo "BUILD_VARS=$(BUILD_VARS)"
	@echo "TARGET=$(TARGET)"
	@echo "SOURCE_C=$(SOURCE_C)"
	@echo "OUT_DIR=$(OUT_DIR)"
	@echo "OUTPUT_ELF=$(OUTPUT_ELF)"
	@echo "OUTPUT_GBA=$(OUTPUT_GBA)"
	@echo "TIME_SCALE=$(TIME_SCALE)"
	@echo "GBAFIX=$(GBAFIX)"
