# ==== CONFIG ====

DEVKITPRO ?= /opt/devkitpro
DEVKITARM := $(DEVKITPRO)/devkitARM
LIBGBA := $(DEVKITPRO)/libgba

CC := $(DEVKITARM)/bin/arm-none-eabi-g++
OBJCOPY := $(DEVKITARM)/bin/arm-none-eabi-objcopy

# ==== BUILD VARS (GENERATED BY TRANSPILER) ====

-include build/build_vars.mk

# Fallbacks
TARGET ?= game
SOURCE_C ?= build/game.c
OUTPUT_ELF ?= $(TARGET).elf
OUTPUT_GBA ?= $(TARGET).gba
TIME_SCALE ?= 1.0

CFLAGS := -x c++ -std=gnu++17 \
          -mthumb -mthumb-interwork \
          -O2 -fno-exceptions -fno-rtti \
          -I$(LIBGBA)/include \
          -I./runtime \
          -DTIME_SCALE=$(TIME_SCALE)

LDFLAGS := -specs=gba.specs \
           -L$(LIBGBA)/lib \
           -lgba -lm

# ==== SOURCES ====

RUNTIME_SRC := \
    runtime/arduboy_compat.c \
    runtime/graphics.c \
    runtime/input.c \
    runtime/audio.c \
    runtime/gba_main.c

# ==== BUILD ====

all: $(OUTPUT_GBA)

$(OUTPUT_ELF): $(SOURCE_C) $(RUNTIME_SRC)
	@mkdir -p "$(dir $(OUTPUT_ELF))"
	$(CC) $(CFLAGS) $^ -o $@ $(LDFLAGS)

$(OUTPUT_GBA): $(OUTPUT_ELF)
	@mkdir -p "$(dir $(OUTPUT_GBA))"
	$(OBJCOPY) -O binary $< $@

# ==== CLEAN ====

clean:
	rm -f *.elf *.gba *.sav *.srm *.sa1 *.flash *.eep
	rm -f build/*.c
	rm -f build/*.o
	rm -f build/*.s
	rm -f build/*.ii
	rm -f build/*.mk
	find . -type f \( -name "*.sav" -o -name "*.srm" -o -name "*.sa1" -o -name "*.flash" -o -name "*.eep" \) -delete 2>/dev/null || true

# ==== DEBUG ====

print-vars:
	@echo "TARGET=$(TARGET)"
	@echo "SOURCE_C=$(SOURCE_C)"
	@echo "OUTPUT_ELF=$(OUTPUT_ELF)"
	@echo "OUTPUT_GBA=$(OUTPUT_GBA)"
	@echo "TIME_SCALE=$(TIME_SCALE)"
