DEVKITPRO ?= /opt/devkitpro
DEVKITARM ?= $(DEVKITPRO)/devkitARM
LIBGBA := $(DEVKITPRO)/libgba

# Generated by transpiler/main.py
# Falls back to "game" if the transpiler has not been run yet.
-include build/build_vars.mk

TARGET ?= game
SOURCE_C ?= build/game.c

CC = $(DEVKITARM)/bin/arm-none-eabi-gcc
OBJCOPY = $(DEVKITARM)/bin/arm-none-eabi-objcopy

CFILES = \
$(SOURCE_C) \
runtime/arduboy_compat.c \
runtime/graphics.c \
runtime/input.c \
runtime/audio.c \
runtime/gba_main.c

INCLUDES = -I$(LIBGBA)/include -I./runtime
LIBS = -L$(LIBGBA)/lib -lgba

CFLAGS = -mthumb -mthumb-interwork -O2 $(INCLUDES)
LDFLAGS = -specs=gba.specs $(LIBS)

all:
	$(CC) $(CFLAGS) $(CFILES) -o $(TARGET).elf $(LDFLAGS)
	$(OBJCOPY) -O binary $(TARGET).elf $(TARGET).gba

clean:
	rm -f *.elf *.gba
	rm -f build/*.o
